import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import './globals.scss';
import { AuthProvider } from '@/contexts/AuthContext';


export const metadata: Metadata = {
  title: "Healtrack Ai",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={inter.variable}>
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
